src/Entity/Item.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ItemRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ItemRepository::class)
 * @Vich\Uploadable
 */
class Item
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="boolean")
     */
    private $en_vente;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file;

    /**
     * @Vich\UploadableField(mapping="items_images", fileNameProperty="file")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Categorie::class, inversedBy="items")
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="item")
     */
    private $commentaires;

    /**
     * @ORM\Column(type="boolean")
     */
    private $portfolio = true;

    public function __construct()
    {
        $this->categorie = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEnVente(): ?bool
    {
        return $this->en_vente;
    }

    public function setEnVente(bool $en_vente): self
    {
        $this->en_vente = $en_vente;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile(File $file = null)
    {
        $this->imageFile = $file;

        // VERY IMPORTANT
        // It is required that at least one field changes if you are using Doctrine
        // otherwise the event listeners won't be called and the file will be lost
        if ($file) {
            $this->created_at = new \DateTime('now');
        }
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): self
    {
        $this->categorie->removeElement($categorie);

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setItem($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getItem() === $this) {
                $commentaire->setItem(null);
            }
        }

        return $this;
    }

    public function getPortfolio(): ?bool
    {
        return $this->portfolio;
    }

    public function setPortfolio(bool $portfolio): self
    {
        $this->portfolio = $portfolio;

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $aPropos;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $facebook;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $twitter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Discord;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telegram;

    /**
     * @ORM\OneToMany(targetEntity=Item::class, mappedBy="user", orphanRemoval=true)
     */
    private $items;

    /**
     * @ORM\OneToMany(targetEntity=BlogPost::class, mappedBy="user", orphanRemoval=true)
     */
    private $blogPosts;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $github;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $linkedin;

    public function __construct()
    {
        $this->items = new ArrayCollection();
        $this->blogPosts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAPropos(): ?string
    {
        return $this->aPropos;
    }

    public function setAPropos(?string $aPropos): self
    {
        $this->aPropos = $aPropos;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    public function getDiscord(): ?string
    {
        return $this->Discord;
    }

    public function setDiscord(?string $Discord): self
    {
        $this->Discord = $Discord;

        return $this;
    }

    public function getTelegram(): ?string
    {
        return $this->telegram;
    }

    public function setTelegram(?string $telegram): self
    {
        $this->telegram = $telegram;

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setUser($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getUser() === $this) {
                $item->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|BlogPost[]
     */
    public function getBlogPosts(): Collection
    {
        return $this->blogPosts;
    }

    public function addBlogPost(BlogPost $blogPost): self
    {
        if (!$this->blogPosts->contains($blogPost)) {
            $this->blogPosts[] = $blogPost;
            $blogPost->setUser($this);
        }

        return $this;
    }

    public function removeBlogPost(BlogPost $blogPost): self
    {
        if ($this->blogPosts->removeElement($blogPost)) {
            // set the owning side to null (unless already changed)
            if ($blogPost->getUser() === $this) {
                $blogPost->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function __toString()
    {
        return $this->email;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getGithub(): ?string
    {
        return $this->github;
    }

    public function setGithub(string $github): self
    {
        $this->github = $github;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\BlogPostRepository;
use App\Repository\ItemRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(
        ItemRepository $ItemRepository,
        BlogPostRepository $BlogPostRepository,
        UserRepository $userRepository
    ): Response {
        return $this->render('home/index.html.twig', [
            'items' => $ItemRepository->lasItems(),
            'blogposts' => $BlogPostRepository->lastPost(),
            'modo' => $userRepository->getModo(),
        ]);
    }
}

templates/home/cta.html.twig
<section id="cta" class="section-bg">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h3 class="mb-3">Call to Action</h3>
            <h4>Find Out More...</h4>
            <p>
                Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque
                vitae autem.
                <br>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius nihil illum odit quo nesciunt, amet vel
                tempora! Quos quasi doloribus officiis minus! Ea ab deserunt necessitatibus perspiciatis. Accusamus,
                iure recusandae.
            </p>
        </div>

    </div>
</section>

templates/home/hero.html.twig
<section id="hero" class="d-flex align-items-center">

    <div class="container">
        <div class="row">
            <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
                <h1 data-aos="fade-up">{{ site_name }}</h1>
                <h1 data-aos="fade-up">{{ site_slogan }}</h1>
                <h2 data-aos="fade-up" data-aos-delay="400">{{ site_accroche }}</h2>
                <div data-aos="fade-up" data-aos-delay="800">
                    <a href="{{ path('portfolio') }}" class="btn-get-started scrollto">Porfolio</a>
                </div>
            </div>
            <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="fade-left" data-aos-delay="200">
                <img src="{{ asset('img/hero-img.png') }}" class="img-fluid animated" alt="Hero">
            </div>
        </div>
    </div>

</section>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ site_name }} - Welcome!{% endblock %}

{% block body %}

    {% include('header.html.twig') %}

    <!-- ======= Hero Section ======= -->
        {% include('home/hero.html.twig') %}
    <!-- End Hero -->

    <main id="main">

        <!-- ======= LastItems section ======= -->
            {% include('home/cta.html.twig') %}
        <!-- End lastItems Section -->
        
        <!-- ======= LastItems section ======= -->
            {% include('home/lastItems.html.twig') %}
        <!-- End lastItems Section -->

        <!-- ======= Last news section ======= -->
            {% include('home/lastNews.html.twig') %}
        <!-- End More Services Section -->

        <!-- ======= Contact Section ======= -->
            {% include('home/prefooter.html.twig') %}
        <!-- End Contact Section -->

    </main><!-- End #main -->

    {% include('footer.html.twig') %}

{% endblock %}

templates/home/lastItems.html.twig
<section id="items" class="services">
    <div class="container">

        <div class="section-title" data-aos="fade-up">
            <h2>Items</h2>
            <p>Magnam dolores commodi suscipit eius consequatur ex aliquid fug</p>
        </div>

        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for item in items %}
                <div class="col">
                    <div class="card h-100" data-aos="fade-up" data-aos-delay="100">
                        <img src="{{ vich_uploader_asset(item, 'imageFile') | imagine_filter('miniatureHome') }}" class="card-img-top" alt="{{ item.nom }}">
                        <div class="card-body">
                            <a href="{{ path('detailitem', {'slug': item.slug}) }}">
                                <h5 class="card-title">{{ item.nom }}</h5>
                            </a>
                            <p class="card-text">
                                {{ item.description|u.truncate(100, '...', false)|raw }}
                            </p>
                        </div>
                        <div class="border-top pt-1 pb-2 px-3">
                            <small class="text-muted fst-italic">Posted on {{ item.createdAt|date('Y/m/d') }}</small>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="text-center mt-4">
            <a href="{{ path('items') }}" class="btn btn-lg btn-outline-primary">&#8594; See all items</a>
        </div>

    </div>
</section>

templates/home/lastNews.html.twig
<section id="lastnews" class="more-services">
    <div class="container">

        <div class="section-title" data-aos="fade-up">
            <h2>Last news</h2>
            <p>Magnam dolores commodi suscipit eius consequatur ex aliquid fug</p>
        </div>

        <div class="row">
            {% for blogpost in blogposts %}
            <div class="col-sm-12 col-md-6">
                <div class="card h-100" data-aos="fade-up" data-aos-delay="100">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{ path('detailnews', {'slug': blogpost.slug}) }}">{{ blogpost.titre }}</a>
                        </h5>
                        <p class="card-text">
                            {{ blogpost.contenu|u.truncate(200, '...', false)|raw }}
                        </p>
                        <div class="read-more d-flex justify-content-between align-items-center">
                            <span>
                                <a href="">Posted on {{ blogpost.createdAt|date('Y-m-d') }}</a>
                            </span>
                            <a href="{{ path('detailnews', {'slug': blogpost.slug}) }}"><i class="bi bi-arrow-right"></i> Read More</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="text-center mt-4">
            <a href="{{ path('news') }}" class="btn btn-lg btn-outline-primary">&#8594; See all news</a>
        </div>

    </div>
</section>

templates/home/prefooter.html.twig
<section id="contact" class="contact">

    <div class="container">
        <div class="row">

            <div class="col-lg-8 col-md-6" data-aos="fade-up" data-aos-delay="100">
                <div class="contact-about">
                    <h3>{{ site_name }}</h3>
                    <p>
                        {{ modo.description|raw }}
                    </p>
                    <div class="social-links">
                        <a href="{{ modo.facebook}}" class="facebook my-1"><i class="bi bi-facebook"></i></a>
                        <a href="{{ modo.twitter }}" class="twitter my-1"><i class="bi bi-twitter"></i></a>
                        <a href="{{ modo.github }}" class="github my-1"><i class="bi bi-github"></i></a>
                        <a href="{{ modo.linkedin }}" class="linkedin my-1"><i class="bi bi-linkedin"></i></a>
                        <a href="{{ modo.discord }}" class="discord my-1"><i class="bi bi-discord"></i></a>
                        <a href="{{ modo.telegram }}" class="telegram my-1"><i class="bi bi-telegram"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 mt-4 mt-md-0" data-aos="fade-up" data-aos-delay="200">
                <div class="info">
                    <div>
                        <i class="ri-map-pin-line"></i>
                        <p>{{ modo.adresse}}</p>
                    </div>

                    <div>
                        <i class="ri-mail-send-line"></i>
                        <p>{{ modo.email }}</p>
                    </div>

                    <div>
                        <i class="ri-phone-line"></i>
                        <p>{{ modo.telephone }}</p>
                    </div>

                </div>
            </div>

            {#
            <div class="col-lg-5 col-md-12" data-aos="fade-up" data-aos-delay="300">
                <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                    <div class="form-group">
                        <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control" name="email" id="email" placeholder="Your Email"
                            required>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject"
                            required>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="message" rows="5" placeholder="Message"
                            required></textarea>
                    </div>
                    <div class="my-3">
                        <div class="loading">Loading</div>
                        <div class="error-message"></div>
                        <div class="sent-message">Your message has been sent. Thank you!</div>
                    </div>
                    <div class="text-center"><button type="submit">Send Message</button></div>
                </form>
            </div>
            #}

        </div>
    </div>

</section>