src/Entity/Item.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ItemRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ItemRepository::class)
 * @Vich\Uploadable
 */
class Item
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="boolean")
     */
    private $en_vente;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file;

    /**
     * @Vich\UploadableField(mapping="items_images", fileNameProperty="file")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Categorie::class, inversedBy="items")
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="item")
     */
    private $commentaires;

    /**
     * @ORM\Column(type="boolean")
     */
    private $portfolio = true;

    public function __construct()
    {
        $this->categorie = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEnVente(): ?bool
    {
        return $this->en_vente;
    }

    public function setEnVente(bool $en_vente): self
    {
        $this->en_vente = $en_vente;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile(File $file = null)
    {
        $this->imageFile = $file;

        // VERY IMPORTANT
        // It is required that at least one field changes if you are using Doctrine
        // otherwise the event listeners won't be called and the file will be lost
        if ($file) {
            $this->created_at = new \DateTime('now');
        }
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): self
    {
        $this->categorie->removeElement($categorie);

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setItem($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getItem() === $this) {
                $commentaire->setItem(null);
            }
        }

        return $this;
    }

    public function getPortfolio(): ?bool
    {
        return $this->portfolio;
    }

    public function setPortfolio(bool $portfolio): self
    {
        $this->portfolio = $portfolio;

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }
}

src/Controller/ItemController.php
<?php

namespace App\Controller;

use App\Entity\Item;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\ItemRepository;
use App\Service\CommentaireService;
use App\Repository\CommentaireRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ItemController extends AbstractController
{
    /**
     * @Route("/items", name="items")
     */
    public function index(
        ItemRepository $itemRepository,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        $data = $itemRepository->findBy([], ['id' => 'DESC']);

        $items = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1),
            5
        );

        return $this->render('item/index.html.twig', [
            'items' => $items,
            'current_menu' => 'items',
        ]);
    }

    /**
     * @Route("/items/{slug}", name="detailitem")
     */
    public function detail(
        Item $item,
        Request $request,
        CommentaireService $commentaireService,
        CommentaireRepository $commentaireRepository
    ): Response {
        $commentaires = $commentaireRepository->findCommentaires($item);
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentaire = $form->getData();
            $commentaireService->persistCommentaire($commentaire, null, $item);

            return $this->redirectToRoute('detailitem', ['slug' => $item->getSlug()]);
        }

        return $this->render('item/detail.html.twig', [
            'item' => $item,
            'form' => $form->createView(),
            'commentaires' => $commentaires,
        ]);
    }
}

templates/item/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ site_name }} - Item: {{ item.nom }}{% endblock %}

{% block body %}

{% include('header.html.twig') %}

<main id="main">

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center">
                <h2>Item: {{ item.nom }}</h2>
                <ol>
                    <li><a href="{{ path('home') }}">Home</a></li>
                    <li><a href="{{ path('items') }}">Items</a></li>
                    <li>Item: {{ item.nom }}</li>
                </ol>
            </div>
        </div>
    </section><!-- End Breadcrumbs Section -->

    <section class="inner-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-12">
                    <h2>{{ item.nom }}</h2>
                    {% for categorie in item.categorie %}
                        <span class="badge bg-secondary">{{ categorie.nom }}</span>
                    {% endfor %}

                    <p class="fs-lg text-muted">
                        {{ item.description }}
                    </p>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <h6 class="d-flex mb-0 text-uppercase">
                                Published on
                                <span class="ms-auto">{{ item.createdAt|date('Y-m-d') }}</span>
                            </h6>
                        </li>
                        {% if item.enVente %}
                            <li class="list-group-item">
                                <h6 class="d-flex mb-0 text-uppercase">
                                    Available for sale
                                    <span class="ms-auto">{{ item.prix|format_currency('USD', locale='en_US') }}</span>
                                </h6>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-lg-7 col-sm-12 d-flex justify-content-center">
                    <img class="img-fluid rounded" src="{{ vich_uploader_asset(item, 'imageFile') | imagine_filter('miniatureItemPage') }}" alt="{{ item.nom }}">
                </div>
            </div>

            {% include 'commentaire/form.html.twig' %}

            {% include 'commentaire/commentaires.html.twig' %}
        </div>
    </section>
</main>

{% include('footer.html.twig') %}

{% endblock %}

templates/item/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ site_name }} - Items{% endblock %}

{% block body %}

{% include('header.html.twig') %}

<main id="main">

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center">
                <h2>Items</h2>
                <ol>
                    <li><a href="{{ path('home') }}">Home</a></li>
                    <li>Items</li>
                </ol>
            </div>
        </div>
    </section><!-- End Breadcrumbs Section -->

    <section class="inner-page">
        <div class="container">
            {% for item in items %}
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-2">
                        <div class="card-body">
                            <img src="{{ vich_uploader_asset(item, 'imageFile') | imagine_filter('miniatureItems') }}" class="img-fluid rounded-start" alt="{{ item.nom }}">
                        </div>
                    </div>
                    <div class="col-md-10">
                        <div class="card-body">
                            <a href="{{ path('detailitem', {'slug': item.slug}) }}">
                                <h4 class="card-title">{{ item.nom }}</h4>
                            </a>
                            <p class="card-text">
                                {{ item.description|u.truncate(300, '...', false) }}
                            </p>
                            <p class="card-text">
                                <small class="text-muted">Published on {{ item.createdAt|date('Y-m-d') }}</small>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="d-flex justify-content-center mt-5">
            {% do items.setPageRange(2) %}
            {{ knp_pagination_render(items, 'pagination.html.twig') }}
        </div>

    </section>
</main>

{% include('footer.html.twig') %}

{% endblock %}